In [79]:
# !pip install "tensorflow-text"
# !pip install einops

In [80]:
#EXP
# import pandas as pd
# convert csv to txt
def csv_to_txt( path = '/content/captions_csv.csv'):
  import pandas as pd
  data = pd.read_csv(path)
  data.dropna()
  print(data.head())
  column_contents = data['Caption'].astype(str).values.tolist()
  column_contents
  # Write the column contents to a text file
  with open('captions.txt', 'w', encoding='utf-8') as f:
    for item in column_contents:
        item = item.encode('utf-8').decode('unicode_escape')
        f.write("%s\n" % item)
# csv_to_txt()

In [146]:
#CONSTANTS
path_to_data_file = './bookstxt.txt'
DATA_LIMIT = 40
model_root_path = '../models/attention'
model_path = f'{model_root_path}/{DATA_LIMIT}_model.tf'
vectorizer_config_path = '../models/attention/text_processor_config.pkl'
vectorizer_weights_path = '../models/attention/text_processor_weights.pkl'

In [81]:
import numpy as np

import typing
from typing import Any, Tuple

import einops
# import matplotlib.pyplot as plt
# import matplotlib.ticker as ticker

import tensorflow as tf
import tensorflow_text as tf_text
import pathlib
import pickle

In [82]:
# path_to_zip = tf.keras.utils.get_file('spa-eng.zip', origin='http://storage.googleapis.com/download.tensorflow.org/data/spa-eng.zip', extract=True)


In [83]:
path_to_file = pathlib.Path(path_to_data_file)
# path_to_file = pathlib.Path(path_to_zip).parent/'spa-eng/spa.txt'
def load_data(path):
  text = path.read_text(encoding='utf-8')
  lines = text.splitlines()
  print(type(lines))
  pairs = [line.split('\t') for line in lines]
  pairs = pairs[:DATA_LIMIT]
  # text = np.array(pairs)

  text = np.array([target for target in pairs])

  return text

data = load_data(path_to_file)
print(data.shape)

data = data[:, 0]
print(data.shape)
print(data)

<class 'list'>
(40, 1)
(40,)
['Charles Bukowski was an alcoholic, a womanizer, a chronic gambler, a lout, a cheapskate, a deadbeat, and on his worst days, a poet. He’s probably the last person on earth you would ever look to for life advice or expect to see in any sort of self-help book. Which is why he’s the perfect place to start. Bukowski wanted to be a writer. But for decades his work was rejected by almost every magazine, newspaper, journal, agent, and publisher he submitted to. His work was horrible, they said. Crude. Disgusting. Depraved. And as the stacks of rejection slips piled up, the weight of his failures pushed him deep into an alcohol-fueled depression that would follow him for most of his life. Bukowski had a day job as a letter-filer at a post office. He got paid shit money and spent most of it on booze. He gambled away the rest at the racetrack. At night, he would drink alone and sometimes hammer out poetry on his beat-up old typewriter. Often, he’d wake up on the flo

In [84]:
len(data)

40

In [85]:
BUFFER_SIZE = len(data)
BATCH_SIZE = 16
is_train = np.random.uniform(size=(len(data),)) < 0.8
train_raw = tf.data.Dataset.from_tensor_slices(data[is_train]).shuffle(BUFFER_SIZE).batch(BATCH_SIZE)
val_raw = tf.data.Dataset.from_tensor_slices(data[~is_train] ).shuffle(BUFFER_SIZE).batch(BATCH_SIZE)

In [86]:
len(train_raw)

3

In [87]:
for context_string in train_raw.take(1):
  print(context_string[:])
  break

tf.Tensor(
[b'In the 1950s, a Polish psychologist named Kazimierz Dabrowski studied World War II survivors and how they\xe2\x80\x99d coped with traumatic experiences in the war. This was Poland, so things had been pretty gruesome. These people had experienced or witnessed mass starvation, bombings that turned cities to rubble, the Holocaust, the torture of prisoners of war, and the rape and/or murder of family members, if not by the Nazis, then a few years later by the Soviets. As Dabrowski studied the survivors, he noticed something both surprising and amazing. A sizable percentage of them believed that the wartime experiences they\xe2\x80\x99d suffered, although painful and indeed traumatic, had actually caused them to become better, more responsible, and yes, even happier people. Many described their lives before the war as if they\xe2\x80\x99d been different people then: ungrateful for and unappreciative of their loved ones, lazy and consumed by petty problems, entitled to all they

In [88]:
example_text = tf.constant("You have been invited to think of the two systems as agents within the mind.")
print(example_text.numpy())
print(tf_text.normalize_utf8(example_text, 'NFKD').numpy())

b'You have been invited to think of the two systems as agents within the mind.'
b'You have been invited to think of the two systems as agents within the mind.'


In [89]:
@tf.keras.utils.register_keras_serializable(package='Custom', name=None)
def tf_lower_and_split_punct(text):
  # Split accented characters
  text = tf_text.normalize_utf8(text, 'NFKD')
  text = tf.strings.lower(text)
  # Keep space, a to z, and select punctuation.
  text = tf.strings.regex_replace(text, '[^ a-z.?!,¿]', '')
  # add space arround punctuation
  text = tf.strings.regex_replace(text, '[.?!,¿]', r' \0 ')
  # remove non-desplayable characters
  text = tf.strings.regex_replace(text, '[^\x00-\x7F]+', '')
  #Strip white space
  text = tf.strings.strip(text)

  text = tf.strings.join(['[START]', text, '[END]'], separator=' ')
  return text


In [90]:
print(example_text.numpy().decode())
print(tf_lower_and_split_punct(example_text).numpy().decode())

You have been invited to think of the two systems as agents within the mind.
[START] you have been invited to think of the two systems as agents within the mind . [END]


In [91]:
#Text Vectorization for the context text data (spainish)
max_vocab_size = 30000
context_text_processor = tf.keras.layers.TextVectorization(standardize=tf_lower_and_split_punct, max_tokens=max_vocab_size, ragged=True)

In [92]:
context_text_processor.adapt(train_raw)
print(context_text_processor.get_vocabulary()[:20])


['', '[UNK]', '.', ',', 'the', 'and', 'to', 'a', 'of', 'that', 'you', 'in', 'i', 'was', 'it', 'on', 'his', 'is', 'for', 'as']


In [93]:
# pk.dump(context_text_processor.get_config(), open('text_processor_config.pkl', 'wb'))

In [94]:
# now layers can convert batch of strings to batch of token ids
example_tokens = context_text_processor(context_string)
print(example_tokens[:3, :])

<tf.RaggedTensor [[24, 11, 4, 223, 3, 7, 1106, 1079, 1195, 1300, 632, 449, 151, 154, 1345,
  445, 5, 59, 220, 1640, 20, 432, 605, 11, 4, 154, 2, 29, 13, 1107, 3, 32,
  80, 39, 127, 226, 1391, 2, 288, 42, 39, 1486, 26, 710, 1239, 897, 3, 1729,
  9, 280, 1681, 6, 1000, 3, 4, 1359, 3, 4, 800, 8, 1090, 8, 154, 3, 5, 4,
  1058, 680, 1200, 8, 99, 536, 3, 37, 54, 73, 4, 1192, 3, 56, 7, 202, 93,
  245, 73, 4, 920, 2, 19, 632, 449, 4, 445, 3, 21, 1174, 68, 113, 857, 5,
  399, 2, 7, 939, 1127, 8, 53, 179, 9, 4, 735, 605, 220, 293, 3, 682, 518,
  5, 562, 432, 3, 39, 184, 652, 53, 6, 100, 393, 3, 45, 306, 3, 5, 692, 3,
  124, 1376, 42, 2, 97, 1589, 76, 167, 142, 4, 154, 19, 37, 220, 127, 1577,
  42, 56, 770, 18, 5, 778, 8, 76, 1255, 162, 3, 551, 5, 382, 73, 510, 75, 3,
  1510, 6, 31, 220, 127, 585, 2, 128, 4, 154, 52, 203, 45, 1652, 3, 45, 131,
  8, 2, 2, 2, 25]                                                           ,
 [24, 368, 567, 93, 269, 1704, 179, 9, 1710, 13, 63, 347, 2, 1564, 179, 9,
  

In [95]:
#The get_vocabulary method can be used to convert token IDs back to text:
context_vocab = np.array(context_text_processor.get_vocabulary())
tokens = context_vocab[example_tokens[0].numpy()]
tokens = ' '.join(tokens)
print(tokens)

[START] in the s , a polish psychologist named kazimierz dabrowski studied world war ii survivors and how theyd coped with traumatic experiences in the war . this was poland , so things had been pretty gruesome . these people had experienced or witnessed mass starvation , bombings that turned cities to rubble , the holocaust , the torture of prisoners of war , and the rape andor murder of family members , if not by the nazis , then a few years later by the soviets . as dabrowski studied the survivors , he noticed something both surprising and amazing . a sizable percentage of them believed that the wartime experiences theyd suffered , although painful and indeed traumatic , had actually caused them to become better , more responsible , and yes , even happier people . many described their lives before the war as if theyd been different people then ungrateful for and unappreciative of their loved ones , lazy and consumed by petty problems , entitled to all theyd been given . after the wa

In [96]:

def process_text(context):
  target = context_text_processor(context)
  context = context_text_processor(context).to_tensor()
  # print(type(context))
  # targ_in = target[:, :-1].to_tensor() #take everthing in axiz = 0 and take everything except the last in axis = 2
  # targ_in = target[:, 1:].to_tensor()
  # targ_out = target[:, :-1].to_tensor()
  target = target[:, 1:]
  targ_in = target[:, :-1].to_tensor() #take everthing in axiz = 0 and take everything except the last in axis = 2
  targ_out = target[:, 1:].to_tensor()

  

  print('process_text')

  return (context, targ_in), targ_out

train_ds = train_raw.map(process_text, tf.data.AUTOTUNE)
val_ds = val_raw.map(process_text, tf.data.AUTOTUNE)

process_text
process_text


In [97]:
len(train_ds)


3

In [98]:
for (example_context_tokens, target_in_tokens), target_out_tokens in train_ds.take(2):

  print(example_context_tokens[0, :10].numpy(), example_context_tokens[0, :].numpy().shape)
  print(target_in_tokens[0, :10].numpy(), target_in_tokens[0, :].numpy().shape)
  print(target_out_tokens[0, :10].numpy(), target_out_tokens[0, :].numpy().shape)
  print()

[  24   42 1809   58  391   54  172    7   90    2] (219,)
[  42 1809   58  391   54  172    7   90    2   11] (217,)
[1809   58  391   54  172    7   90    2   11  111] (217,)

[ 24  55   8  70  41 226 209  22  55  80] (225,)
[ 55   8  70  41 226 209  22  55  80  44] (223,)
[  8  70  41 226 209  22  55  80  44  67] (223,)



In [99]:
# target_in_tokens = target_in_tokens + 1
# print(target_in_tokens[0, :10].numpy(),'\n', target_out_tokens[0, :10].numpy())

In [100]:
'''
The encoder:
  1. Takes a list of token IDs (from context_text_processor).
  2. Looks up an embedding vector for each token (Using a layers.Embedding).
  3. Processes the embeddings into a new sequence (Using a bidirectional layers.GRU).
  4. Returns the processed sequence. This will be passed to the attention head.
'''


class Encoder(tf.keras.layers.Layer):
  def __init__(self, text_processor, units):
    super(Encoder, self).__init__()
    self.text_processor = text_processor
    self.vocab_size = text_processor.vocabulary_size()
    self.units = units

    #The embedding layer converts tokens into vectors
    self.embedding = tf.keras.layers.Embedding(self.vocab_size, self.units, mask_zero=True)

    #The RNN layer processes those vectors sequentially
    self.rnn = tf.keras.layers.Bidirectional(merge_mode='sum', 
                                             layer=tf.keras.layers.GRU(self.units, return_sequences=True, recurrent_initializer='glorot_uniform' ))
  
  def call(self, x):
    x = self.embedding(x)
    x = self.rnn(x)
    # print('call')
    return x

  def convert_input(self, texts):
    texts = tf.convert_to_tensor(texts)
    if len(texts.shape) == 0:
      texts = tf.convert_to_tensor(texts)[tf.newaxis]
    context = self.text_processor(texts).to_tensor()
    context = self(context)
    return context


In [101]:
UNITS = 256

In [102]:
# Encode the input sequence.
encoder = Encoder(context_text_processor, UNITS)
ex_context = encoder(example_context_tokens)

print(f'Context tokens, shape (batch, s): {example_context_tokens.shape}')
print(f'Encoder output, shape (batch, s, units): {ex_context.shape}')

Context tokens, shape (batch, s): (16, 225)
Encoder output, shape (batch, s, units): (16, 225, 256)


In [103]:
class CrossAttention(tf.keras.layers.Layer):
  def __init__(self, units, **kwargs):
    super().__init__()

    self.mha = tf.keras.layers.MultiHeadAttention(key_dim=units, num_heads=1, **kwargs)
    self.layernorm = tf.keras.layers.LayerNormalization()
    self.add = tf.keras.layers.Add()

  def call(self, x, context):
    atten_output, atten_score = self.mha(query=x, value=context, return_attention_scores=True)
    x = self.add([x, atten_output])
    x = self.layernorm(x)
    return x

In [104]:
attention_layer = CrossAttention(UNITS)
# Attend to the encoded tokens
embed = tf.keras.layers.Embedding(context_text_processor.vocabulary_size(),
                                  output_dim=UNITS, mask_zero=True)


In [105]:
'''
The decoder's job is to generate predictions for the next token at each location in the target sequence.
  1. It looks up embeddings for each token in the target sequence.
  2. It uses an RNN to process the target sequence, and keep track of what it has generated so far.
  3. It uses RNN output as the "query" to the attention layer, when attending to the encoder's output.
  4. At each location in the output it predicts the next token.
'''

class Decoder(tf.keras.layers.Layer):
  @classmethod
  def add_method(cls, fun):
    setattr(cls, fun.__name__, fun)
    return fun

  def __init__(self, text_processor, units):
    super(Decoder, self).__init__()
    self.text_processor = text_processor
    self.vocab_size = text_processor.vocabulary_size()
    self.word_to_id = tf.keras.layers.StringLookup(vocabulary=text_processor.get_vocabulary(), mask_token='', oov_token='[UNK]')
    self.id_to_word = tf.keras.layers.StringLookup(vocabulary=text_processor.get_vocabulary(), mask_token='', oov_token='[UNK]', invert=True)
    self.start_token = self.word_to_id('[START]')
    self.end_token = self.word_to_id('[END]')

    self.units = units

    # 1. The embedding layer converts token IDs to vectors
    self.embedding = tf.keras.layers.Embedding(self.vocab_size, self.units, mask_zero=True)
    # 2. The RNN keeps track of what's been generated so far.
    self.rnn = tf.keras.layers.GRU(self.units, return_sequences=True, return_state=True, recurrent_initializer='glorot_uniform')
    #3. The RNN output will be the query for the attention layer.
    self.attention = CrossAttention(self.units)

    # self.fc1 = tf.keras.layers.Dense(self.units, activation='relu')
    # 4. This fully connected layer produces the logits for each output token.
    self.output_layer = tf.keras.layers.Dense(self.vocab_size)

  def call(self, context, x, state=None, return_state=False):
    #Lookup for embeddings
    x = self.embedding(x)
    #Process the target sequence
    x, state = self.rnn(x, initial_state=state)
    #Use the rnn output as the query for the attention over the context
    x = self.attention(x, context)

    # x = self.fc1(x)

    #generate logit predictyions for the next token
    logits = self.output_layer(x)


    if return_state:
      return logits, state
    return logits




In [106]:
decoder = Decoder(context_text_processor, UNITS)

In [107]:
@Decoder.add_method
def get_initial_state(self, context):
  batch_size = tf.shape(context)[0]
  print(batch_size)
  start_tokens = tf.fill([batch_size, 1], self.start_token)

  # print(start_tokens, 'satrt token')
  # print(tf.constant(context), 'context')
  done = tf.zeros([batch_size, 1], dtype=tf.bool)
  embedded = self.embedding(start_tokens)
  return start_tokens, done, self.rnn.get_initial_state(embedded)[0]

# print(example_context_tokens, 'ex_context_tokens')
# ex_context = encoder(example_context_tokens)
# next_token, done, state = decoder.get_initial_state(ex_context)
# print(next_token, state)

In [108]:
@Decoder.add_method
def tokens_to_text(self, tokens):
  words = self.id_to_word(tokens)
  result = tf.strings.reduce_join(words, axis=-1, separator=' ')
  result = tf.strings.regex_replace(result, '^ *\[START\] *', '')
  result = tf.strings.regex_replace(result, ' *\[END\] *$', '')
  return result

# decoder.tokens_to_text(example_context_tokens)

In [109]:
@Decoder.add_method
def get_next_token(self, context, next_token, done, state, temperature = 0.0):

  logits, state = self(context, next_token, state = state, return_state=True) 

  if temperature == 0.0:
    next_token = tf.argmax(logits, axis=-1)
  else:
    logits = logits[:, -1, :]/temperature
    next_token = tf.random.categorical(logits, num_samples=1)

  # If a sequence produces an `end_token`, set it `done`
  # done = done | (next_token == self.end_token)
  # # Once a sequence is done it only produces 0-padding.
  # next_token = tf.where(done, tf.constant(0, dtype=tf.int64), next_token)

  return next_token, done, state

In [110]:
# Setup the loop variables.
next_token, done, state = decoder.get_initial_state(ex_context)
tokens = []

for n in range(10):
  # Run one step.
  next_token, done, state = decoder.get_next_token(
      ex_context, next_token, done, state, temperature=1.0)
  # Add the token to the output.
  tokens.append(next_token)

# Stack all the tokens together.
tokens = tf.concat(tokens, axis=-1) # (batch, t)

# Convert the tokens back to a a string
result = decoder.tokens_to_text(tokens)
result[:3].numpy()

tf.Tensor(16, shape=(), dtype=int32)


array([b'starvation shittons hours absolutely knew forces level commutes arms whose',
       b'question split book too teaching showed ability family rubble her',
       b'vast choices our inherently age together dinners bodyshake got scariest'],
      dtype=object)

In [111]:
class TextGen(tf.keras.Model):
  @classmethod
  def add_method(cls, fun):
    setattr(cls, fun.__name__, fun)
    return fun

  def __init__(self, units, context_text_processor, target_text_processor):
    super().__init__()
    #Build the encoder and the decoder
    self.encoder = Encoder(context_text_processor, units)
    self.decoder = Decoder(context_text_processor, units)

  def call(self, inputs):
    # print("here1")
    context, x = inputs
    # print("here2")

    context = self.encoder(context)
    # print("here3")

    logits = self.decoder(context, x)
    # print("here4")

    try:
      del logits._keras_mask
    except AttributeError:
      pass
    # print("here5", logits)
    return logits
  
  def gen(self,
                texts, *,
                max_length=50,
                temperature=0.0):
    # Process the input texts
    context = self.encoder.convert_input(texts)
    batch_size = tf.shape(texts)[0]

    # Setup the loop inputs
    tokens = []
    attention_weights = []
    next_token, done, state = self.decoder.get_initial_state(context)

    for _ in range(max_length):
      # Generate the next token
      next_token, done, state = self.decoder.get_next_token(context, next_token, done,  state, temperature)

      # Collect the generated tokens
      tokens.append(next_token)
      # attention_weights.append(self.decoder.last_attention_weights)

      # if tf.executing_eagerly() and tf.reduce_all(done):
      #   break

    # Stack the lists of tokens and attention weights.
    tokens = tf.concat(tokens, axis=-1)   # t*[(batch 1)] -> (batch, t)
    # self.last_attention_weights = tf.concat(attention_weights, axis=1)  # t*[(batch 1 s)] -> (batch, t s)

    result = self.decoder.tokens_to_text(tokens)
    return result

    

In [112]:
model = TextGen(UNITS, context_text_processor, context_text_processor)

In [113]:
def masked_loss(y_true, y_pred):
    # Calculate the loss for each item in the batch.
    loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(
        from_logits=True, reduction='none')
    # print(y_true.shape, y_pred.shape, "masked_loss")
    loss = loss_fn(y_true, y_pred)
    

    # Mask off the losses on padding.
    mask = tf.cast(y_true != 0, loss.dtype)
    loss *= mask

    # Return the total.
    return tf.reduce_sum(loss)/tf.reduce_sum(mask)

In [114]:
#custom accuracy
def masked_acc(y_true, y_pred):
  # Calculate the loss for each item in the batch
  y_pred = tf.argmax(y_pred, axis=-1)
  y_pred = tf.cast(y_pred, y_true.dtype)

  match = tf.cast(y_true == y_pred, dtype=tf.float32)
  mask = tf.cast(y_true != 0, tf.float32)

  return tf.reduce_sum(match) / tf.reduce_sum(mask)


In [115]:
model.compile(optimizer='adam', loss=masked_loss, metrics=[masked_acc, masked_loss])

In [116]:
vocab_size = 1.0 * context_text_processor.vocabulary_size()

{"expected_loss": tf.math.log(vocab_size).numpy(),
 "expected_acc": 1/vocab_size}

{'expected_loss': 7.527794, 'expected_acc': 0.0005379236148466917}

In [117]:
# model.evaluate(val_ds, steps=20, return_dict=True)

In [147]:
checkpoint_path = model_root_path + f"/{DATA_LIMIT}_cp.ckpt"
cp_callback = tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_path, save_best_only=True, verbose=1)

In [148]:
history = model.fit(
    train_ds.repeat(), 
    epochs=10,
    steps_per_epoch = 20,
    validation_data=val_ds,
    validation_steps = 20,
    callbacks=[
        tf.keras.callbacks.EarlyStopping(patience=5, monitor='masked_acc'), cp_callback])

Epoch 1/10
20/20 [==============================] - ETA: 0s - loss: 0.0661 - masked_acc: 0.9997 - masked_loss: 0.0660WARNING:tensorflow:Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches (in this case, 20 batches). You may need to use the repeat() function when building your dataset.



Epoch 1: val_loss improved from inf to 8.95022, saving model to ../models/attention\40_cp.ckpt


INFO:tensorflow:Assets written to: ../models/attention\40_cp.ckpt\assets


INFO:tensorflow:Assets written to: ../models/attention\40_cp.ckpt\assets


20/20 [==============================] - 116s 6s/step - loss: 0.0661 - masked_acc: 0.9997 - masked_loss: 0.0660 - val_loss: 8.9502 - val_masked_acc: 0.0606 - val_masked_loss: 8.9502
Epoch 2/10
20/20 [==============================] - ETA: 0s - loss: 0.0489 - masked_acc: 1.0000 - masked_loss: 0.0486WARNING:tensorflow:Can save best model only with val_loss available, skipping.


20/20 [==============================] - 80s 4s/step - loss: 0.0489 - masked_acc: 1.0000 - masked_loss: 0.0486
Epoch 3/10
20/20 [==============================] - ETA: 0s - loss: 0.0387 - masked_acc: 1.0000 - masked_loss: 0.0388WARNING:tensorflow:Can save best model only with val_loss available, skipping.


20/20 [==============================] - 73s 4s/step - loss: 0.0387 - masked_acc: 1.0000 - masked_loss: 0.0388
Epoch 4/10
20/20 [==============================] - ETA: 0s - loss: 0.0319 - masked_acc: 1.0000 - masked_loss: 0.0319WARNING:tensorflow:Can save best model only with val_loss available, skipping.


20/20 [==============================] - 79s 4s/step - loss: 0.0319 - masked_acc: 1.0000 - masked_loss: 0.0319
Epoch 5/10
20/20 [==============================] - ETA: 0s - loss: 0.0319 - masked_acc: 0.9993 - masked_loss: 0.0326WARNING:tensorflow:Can save best model only with val_loss available, skipping.


20/20 [==============================] - 80s 4s/step - loss: 0.0319 - masked_acc: 0.9993 - masked_loss: 0.0326
Epoch 6/10
20/20 [==============================] - ETA: 0s - loss: 0.0294 - masked_acc: 0.9998 - masked_loss: 0.0298WARNING:tensorflow:Can save best model only with val_loss available, skipping.


20/20 [==============================] - 77s 4s/step - loss: 0.0294 - masked_acc: 0.9998 - masked_loss: 0.0298
Epoch 7/10
20/20 [==============================] - ETA: 0s - loss: 0.0226 - masked_acc: 1.0000 - masked_loss: 0.0226WARNING:tensorflow:Can save best model only with val_loss available, skipping.


20/20 [==============================] - 74s 4s/step - loss: 0.0226 - masked_acc: 1.0000 - masked_loss: 0.0226
Epoch 8/10
20/20 [==============================] - ETA: 0s - loss: 0.0179 - masked_acc: 1.0000 - masked_loss: 0.0179WARNING:tensorflow:Can save best model only with val_loss available, skipping.


20/20 [==============================] - 74s 4s/step - loss: 0.0179 - masked_acc: 1.0000 - masked_loss: 0.0179


In [119]:
result = model.gen(['This was one of my favorite'], max_length=100)
result = result[0].numpy().decode()
print(result)

tf.Tensor(1, shape=(), dtype=int32)
ago , when i was much younger and stupider , i wrote a blog post , and at the end of it i said something like , and as a great philosopher once said with great power comes great responsibility . it sounded nice and authoritative . i couldnt remember who had said it , and my google search had turned up nothing , but i stuck it in there anyway . it fit the post nicely . about ten minutes later , the first comment came in i think the great philosopher youre referring to is uncle ben from


### SAVE 

In [144]:
model_path = f'../models/attention/{DATA_LIMIT}_model.tf'
vectorizer_config_path = '../models/attention/text_processor_config.pkl'
vectorizer_weights_path = '../models/attention/text_processor_weights.pkl'


In [145]:
#save the vectorizaation layer
pickle.dump(context_text_processor.get_config(), open(vectorizer_config_path, 'wb'))
weights = context_text_processor.get_weights()
text_processor_weights = pickle.dump(weights, open(vectorizer_weights_path, "wb"))
#save the final fully trained  model
model.save(model_path)         

INFO:tensorflow:Assets written to: ../models/attention/40_model.tf\assets


INFO:tensorflow:Assets written to: ../models/attention/40_model.tf\assets


In [122]:
# loaded_model = None
# loaded_model = tf.keras.models.load_model(model_path, custom_objects={'tf_lower_and_split_punct': tf_lower_and_split_punct}, compile=False)

In [123]:
# result = loaded_model.predict(['This was one of my favorite'])
# result = result[0].numpy().decode()
# print(result)

In [124]:
# import pickle

# weights = context_text_processor.get_weights()

# text_processor_weights = pickle.dump(weights, open("text_processor_weights.pkl", "wb"))


# loaded_config = pickle.load(open("text_processor_config.pkl", 'rb'))
# loaded_weights = pickle.load(open("text_processor_weights.pkl", 'rb'))
# text_processor = tf.keras.layers.TextVectorization.from_config(loaded_config)
# text_processor.set_weights(loaded_weights)

# new_model = TextGen(UNITS, text_processor, text_processor)

In [125]:
# new_model.load_weights(model_path)

In [126]:
# result = new_model.gen(['Hello world'])
# result = result[0].numpy().decode()
# print(result)

In [136]:
def create_model(path_to_model, path_to_vectorizer_config, path_to_vectorizer_weights):
    loaded_config = pickle.load(open(path_to_vectorizer_config, 'rb'))
    loaded_weights = pickle.load(open(path_to_vectorizer_weights, 'rb'))

    text_processor = tf.keras.layers.TextVectorization.from_config(loaded_config)
    text_processor.set_weights(loaded_weights)

    new_model = TextGen(UNITS, text_processor, text_processor)
    new_model.load_weights(path_to_model)

    return new_model




In [137]:
textGenModel = create_model(path_to_model=model_path, path_to_vectorizer_config='text_processor_config.pkl', path_to_vectorizer_weights='text_processor_weights.pkl')

In [138]:
textGenModel.gen(['This was one of my favorite and'])

tf.Tensor(1, shape=(), dtype=int32)


<tf.Tensor: shape=(1,), dtype=string, numpy=
array([b'ago , when i was much younger and stupider , i wrote a blog post , and at the end of it i said something like , and as a great philosopher once said with great power comes great responsibility . it sounded nice and authoritative . i couldnt remember'],
      dtype=object)>